### ISSUE TITLE
错误提示

### ISSUE THREAD

**Issue by MeowCold** [hellflame/qiniu_manager#1]
XXX@PC:~$ qiniu -l backup
Traceback (most recent call last):
  File "/usr/local/bin/qiniu", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/qiniuManager/run.py", line 138, in main
    qiniu.list(arg[1])
  File "/usr/local/lib/python2.7/dist-packages/qiniuManager/manager.py", line 40, in auth_ok
    return function(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/qiniuManager/manager.py", line 322, in list
    state, data = self.__get_list_in_space(space, is_debug=is_debug)
  File "/usr/local/lib/python2.7/dist-packages/qiniuManager/manager.py", line 363, in __get_list_in_space
    headers={'Authorization': 'QBox {}'.format(self.auth.token_of_request(url))})
  File "/usr/local/lib/python2.7/dist-packages/qiniuManager/http.py", line 144, in request
    self.https_init(host, port)
  File "/usr/local/lib/python2.7/dist-packages/qiniuManager/http.py", line 106, in https_init
    context = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
AttributeError: 'module' object has no attribute 'SSLContext'

**Comment by hellflame** [comment]
额，是不是python的版本低于 2.7.9 ?

[ssl 'module' object has no attribute 'SSLContext'](https://stackoverflow.com/questions/28228214/ssl-module-object-has-no-attribute-sslcontext)

**Comment by MeowCold** [comment]
发现确实低了 是2.7.6 我去升级

**Comment by hellflame** [comment]
我按照链接里面的说法，试着改一下

`ssl.create_default_context()` 代替 `ssl.SSLContext(ssl.PROTOCOL_TLSv1)`

**Comment by MeowCold** [comment]
问个小白问题怎么更新？

**Comment by hellflame** [comment]
![image](https://user-images.githubusercontent.com/7326970/29494054-1f890518-85d5-11e7-8e4c-cdd457ec0108.png)

第一个应该就可以了

**Comment by MeowCold** [comment]
嗯 我试了 最高1.3.2
对了，问下生成的私有空间链接在浏览器可以正常下载但使用 ssh  
示例
root@PC:~# wget http://backup.ybyys.com/qinkup.zip?e=15032416&token=8s2byGum7LQhkPEZSQ54-KdqLLKYK4b:k1-2yACgnrDqPlk-uCdEBbY=

最终总是报错为
已发出 HTTP 请求，正在等待回应... 401 Unauthorized

用户名/密码认证失败。

**Comment by hellflame** [comment]
额，，这里需要的不是用户名和密码验证的吧=。=

![image](https://user-images.githubusercontent.com/7326970/29494373-91a6fd2a-85db-11e7-8ae8-ac476aab6dcc.png)

是按照上面的方法设置密钥的么

**Comment by hellflame** [comment]
浏览器访问结果是

```json
{"error":"download token auth failed"}
```
如果是wget的问题的话，可能需要这样

```bash
wget --content-disposition "http://backup.ybyys.com/qinkup.zip?e=15032416&token=8s2byGum7LQhkPEZSQ54-KdqLLKYK4b:k1-2yACgnrDqPlk-uCdEBbY="
```

或者用提供的命令：

```bash
qiniu -d qinkup.zip
```

仔细看看 [README](https://github.com/hellflame/qiniu_manager/blob/master/README.md) 应该会有很大帮助

**Comment by MeowCold** [comment]
感谢 用你提供的wget方法可以下载了。  
之前遇到的问题是微软子系统ubuntu无法正常升级py之后我换成虚拟机使用ubuntu正常了。
我提问里的示例是删掉了部分密钥的，因为怕被人检索到。之前看到有人专门检索github用户账号密码以及s3相关地址
感谢您能挤出时间给予我帮助，祝颂商祺

**Comment by hellflame** [comment]
好吧=。=
